fund:
  #超时时间
  timeout: 300000
  #定时
  cron: 0 */10 * * * ?
#小熊同学
doctorxiong:
  #获取基金详情
  detail: https://api.doctorxiong.club/v1/fund/detail
  #获取基金基础信息
  fund: https://api.doctorxiong.club/v1/fund
  #获取热门基金
  hot: https://api.doctorxiong.club/v1/fund/hot
  #获取基金排行
  rank: https://api.doctorxiong.club/v1/fund/rank
#东方财富
eastmoney:
  #天天基金网
  fundgz:
    #基金实时信息
    real_time: http://fundgz.1234567.com.cn/js/
  #涨跌
  zd: https://push2.eastmoney.com/api/qt/ulist.np/get?fltt=2&invt=2&fields=f2,f3,f12,f14,f9&cb=?&ut=267f9ad526dbe6b0262ab19316f5a25b&
#通用请求
normal:
  rank: http://vip.stock.finance.sina.com.cn/fund_center/data/jsonp.php/IO.XSRV2.CallbackList['hLfu5s99aaIUp7D4']/NetValueReturn_Service.NetValueReturnOpen?page=1&num=40&sort=form_year&asc=0&ccode=&type2=0&type3=`
