server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /foolish
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    active: dev,fund
  sa-token:
    # token名称 (同时也是cookie名称)
    token-name: cutetoken
    # token前缀
    tokenPrefix: Bearer
    # token有效期，单位s 默认30天, -1代表永不过期
    timeout: 1200
    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
    activity-timeout: -1
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    allow-concurrent-login: true
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
    is-share: true
    # token风格
    token-style: uuid
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: quartzScheduler
            instanceId: AUTO
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
springfox:
  documentation:
    enabled: on

info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'