spring:
  devtools:
    restart:
      enabled: true
      additional-paths: resources/**,static/**,views/**
  datasource:
    username: root
    password: X123qwe
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leek?serverTimezone=UTC