spring:
  config:
    activate:
      on-profile: prod
  devtools:
    restart:
      enabled: true
      additional-paths: resources/**,static/**,views/**
  datasource:
    username: xxx
    password: xxxxxx
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leek?serverTimezone=UTC

knife4j:
  enable: true
  # 开启生产环境屏蔽
  production: true

logging:
  level: info